### PR TITLE
Productionalized sig gen

### PR DESCRIPTION
**Pull request by Raynes**
This didn't really work at all when I used it. Updated so it's py 2/3 compatible and amended it as needed as I set up my new raspbian installation. This should be a more production-ready self-signed sig generator. It works on OS X as well if you install openssl and such.

### CODE REVIEW

**Comment by erik** [comment]
I appreciate you productionizing this, but I'd prefer not to install an executable file by default since this isn't really the standard way of using alexandra and only really applies for development environments.

I'd feel better about updating the gist link in the README to point to this version or fleshing out the README documentation on the subject instead.

**Comment by Raynes** [comment]
So, I don't like naming it 'alexandra', but I'd advocate for having this script installed alongside alexandra, perhaps renamed to `alexandra-sample-conf` or something so it's clear alexandra is not an application itself.

I personally thought it'd accelerate the development process to be able to just be able to:

``` shell
pip install alexandra
alexandra-sample-conf
```

and be up and running without dragging down gists and such. That said, I'm fairly indifferent. If this isn't compelling to you we can just use the gist. Your call.

**Comment by erik** [comment]
Thanks for being understanding. I very much appreciate the contributions, but in this case I still think gist is the right call. We could always revisit this in the future if it does end up being a pain point

**Comment by Raynes** [comment]
See my updates. You'll want to take the code from my fork of your gist, here: https://gist.github.com/Raynes/90e11216466cdd1dc38d

**Comment by erik** [comment]
Awesome, thanks!

**Pull request merged**
